### ISSUE TITLE
no service/user involving nginx-ingress

### ISSUE THREAD

**Issue by Coolfeather2** [daxio/k8s-lemp#15]
tried re-setting up k8s-lemp by following https://github.com/daxio/k8s-lemp/blob/master/USAGE.md exactly and resulting in this error on the nginx cluster/pod:
```
no service with name nginx-ingress/default-http-backend found: services "default-http-backend" is forbidden: 
User "system:serviceaccount:nginx-ingress:default" cannot get services in the namespace "nginx-ingress":
Unknown user "system:serviceaccount:nginx-ingress:default"
```
but the service exists:
![image](https://user-images.githubusercontent.com/14107982/32259090-1416e83c-bef9-11e7-812a-56948ba049c0.png)
as well as the service account:
![image](https://user-images.githubusercontent.com/14107982/32259173-952d1fe0-bef9-11e7-9490-87c1534bb4f7.png)

**Comment by chepurko** [comment]
Looks like I’ll have to bring up a testing cluster and run through the setup again. I don’t see any recent changes in the Kubernetes API that would break these YAMLs... my current stable deployment is on v1.7.2 and it looks like the most recent version is v1.8.2. I tend to stay on one version for a while as the cluster upgrade procedure is still a crapshoot. Will try to spin it up this weekend.

**Comment by Coolfeather2** [comment]
I'll be happy to give you access to the gke project for testing - contact me Coolfeather.o@gmail.com

**Comment by Coolfeather2** [comment]
okay, this is strange - set it up in a new project and it works fine o.O
only difference is there is two clusters compared to one

**Comment by chepurko** [comment]
It's kind of purpose-built for WordPress. But if you have to take out the CMS then you could modify `wp/wp-wd-Deployment.yaml` and remove the `wp` container.
