### ISSUE TITLE
Nginx Liveness Killed

### ISSUE THREAD

**Issue by Coolfeather2** [daxio/k8s-lemp#17]
Nginx Pod having issues
`Liveness probe failed: HTTP probe failed with statuscode: 500`
`Error syncing pod`
`Killing container with id docker://nginx:Container failed liveness probe.. Container will be killed and recreated.`

Log:

nginx | 2018-01-23T05:48:09.717443178Z | I0123 05:48:09.717340 5 main.go:55] Exiting with 0
-- | -- | --
nginx | 2018-01-23T05:48:09.543457439Z | I0123 05:48:09.543326 5 nginx.go:248] NGINX process has stopped
nginx | 2018-01-23T05:48:08.482033037Z | I0123 05:48:08.481838 5 main.go:38] Handled quit, awaiting pod deletion
nginx | 2018-01-23T05:48:08.449144964Z | I0123 05:48:08.448927 5 main.go:36] shutting down Ingress controller...
nginx | 2018-01-23T05:48:07.235330029Z | 2018/01/23 05:48:06 [notice] 15#15: signal process started
nginx | 2018-01-23T05:47:54.978967590Z | I0123 05:47:54.978848 5 nginx.go:237] stopping NGINX process...
nginx | 2018-01-23T05:47:54.974649483Z | I0123 05:47:54.958731 5 controller.go:1192] shutting down controller queues
nginx | 2018-01-23T05:47:54.938986678Z | I0123 05:47:54.938854 5 main.go:47] Received SIGTERM, shutting down
nginx | 2018-01-23T05:47:44.678975559Z | I0123 05:47:44.458710 5 controller.go:1206] starting Ingress controller
nginx | 2018-01-23T05:47:44.027886222Z | I0123 05:47:44.027695 5 nginx.go:172] starting NGINX process...
nginx | 2018-01-23T05:47:43.690317939Z | I0123 05:47:43.690212 5 launch.go:140] validated nginx-ingress/default-http-backend as the default backend
nginx | 2018-01-23T05:47:42.953135808Z | I0123 05:47:42.953008 5 launch.go:304] Running in Kubernetes Cluster version v1.8+ (v1.8.6-gke.0) - git (clean) commit ee9a97661f14ee0b1ca31d6edd30480c89347c79 - platform linux/amd64
nginx | 2018-01-23T05:47:41.435138994Z | I0123 05:47:41.433076 5 launch.go:291] Creating API client for https://10.11.240.1:443
nginx | 2018-01-23T05:47:41.411967533Z | I0123 05:47:41.411857 5 launch.go:116] Watching for ingress class: nginx
nginx | 2018-01-23T05:47:41.137850688Z | I0123 05:47:41.137621 5 launch.go:113] &{NGINX 0.9.0-beta.15 git-a3e86f2 https://github.com/kubernetes/ingress}

Might have to redirect this issue to https://github.com/kubernetes/ingress-nginx

**Comment by Coolfeather2** [comment]
Still occurring, was fixed for a bit, haven't done any changes

**Comment by chepurko** [comment]
Is this the Ingress? I usually solved the problem by deleting and recreating that deployment, but that was a while ago. I believe it had to do with Kubernetes actually, and I’m up to v1.9.1 in my cluster and have not seen the issues in a while.

If you could update your cluster and check again? Unfortunately it’s still an undertaking to update a cluster, but that’s just a Kubernetes thing 😁

**Comment by Coolfeather2** [comment]
I wouldn't have a clue, this was a while ago and not using it anymore
